version: '3.8'

services:
  sqlserver-mcp:
    image: ghcr.io/your-org/sqlserver-mcp:latest
    environment:
      - SQLSERVER_SERVER=your-server.database.windows.net
      - SQLSERVER_DATABASE=your-database
      - SQLSERVER_USERNAME=your-username
      - SQLSERVER_DRIVER=ODBC Driver 18 for SQL Server
      - SQLSERVER_ENCRYPT=yes
      - SQLSERVER_TRUST_CERTIFICATE=no
    secrets:
      - sqlserver_password
    configs:
      - source: sqlserver_config
        target: /app/config/config.yaml
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
      rollback_config:
        parallelism: 1
        delay: 0s
        failure_action: pause
        monitor: 60s
        max_failure_ratio: 0.3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
      placement:
        constraints:
          - node.role == worker
        preferences:
          - spread: node.id
    healthcheck:
      test: ["CMD", "python", "-c", "import health_check; health_check.check_health()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp_network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

secrets:
  sqlserver_password:
    external: true

configs:
  sqlserver_config:
    external: true

networks:
  mcp_network:
    driver: overlay
    attachable: true