# Azure OpenAI Configuration
##azure_openai:
##endpoint: "https://aoai-poc-steve.openai.azure.com/"
##api_key: "4b9ddbd2052a473ebac7d72cd4836888"
##api_version: "2025-01-01-preview"
##deployment_name: "gpt-4o-steve"

azure_openai:
  endpoint: "https://your-azure-openai-endpoint.openai.azure.com"
  api_key: "your-azure-openai-api-key"
  api_version: "2025-04-01-preview"
  deployment_name: "your-deployment-name"

# SQL Server Configuration
sql_server:
  server: "localhost"
  database: "Test_Steve"
  driver: "ODBC Driver 17 for SQL Server"
  use_windows_auth: false # Uses SQL Server login
  username: "your-sql-username" # The SQL user you created
  password: "your-sql-password" # The password you set
  encrypt: "no"
  trust_server_certificate: "yes"

# Databricks Configuration
databricks:
  server_hostname: "your-workspace.cloud.databricks.com"
  http_path: "/sql/1.0/warehouses/your-warehouse-id"
  access_token: "your-databricks-access-token"
  catalog: "your-catalog"
  schema: "your-schema"

# Azure DevOps Configuration
azure_devops:
  organization: "your-azure-devops-org" # Your Azure DevOps organization name

# Web Search Configuration
web_search:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  timeout: 10
  max_results: 10

# Snowflake Configuration
snowflake:
  # Required: Snowflake account identifier
  account: "your-snowflake-account"

  # Required: Snowflake username
  user: "your-snowflake-username"

  # Authentication Method: Username/Password
  password: "your-snowflake-password"

  # Optional: Default connection settings
  database: "your-database"
  schema: "your-schema"
  warehouse: "compute_wh"
  role: "accountadmin"

  # Connection Settings
  timeout: 120
  max_retries: 3
  retry_delay: 5
  pool_size: 5
  pool_timeout: 30

# MCP Server Configuration
mcp_server:
  host: "localhost"
  port: 8000
