# Azure OpenAI Configuration
azure_openai:
  endpoint: "https://aoai-poc-steve.openai.azure.com/"
  api_key: "4b9ddbd2052a473ebac7d72cd4836888"
  api_version: "2025-01-01-preview"
  deployment_name: "gpt-4o-steve"

# SQL Server Configuration
sql_server:
  server: "your-server.database.windows.net"
  database: "your_database"
  username: "your_username"
  password: "your_password"
  driver: "ODBC Driver 18 for SQL Server"

# Databricks Configuration
databricks:
  server_hostname: "your-workspace.cloud.databricks.com"
  http_path: "/sql/1.0/warehouses/your-warehouse-id"
  access_token: "your-access-token"
  catalog: "your_catalog"
  schema: "your_schema"

# MCP Server Configuration
mcp_server:
  host: "localhost"
  port: 8000