version: '3.8'

services:
  snowflake-mcp:
    build: .
    image: snowflake-mcp:latest
    container_name: snowflake-mcp-server
    environment:
      # Required Snowflake connection settings
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      
      # Optional connection settings
      - SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE:-}
      - SNOWFLAKE_SCHEMA=${SNOWFLAKE_SCHEMA:-PUBLIC}
      - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE:-}
      - SNOWFLAKE_ROLE=${SNOWFLAKE_ROLE:-}
      
      # Connection tuning (optional)
      - SNOWFLAKE_TIMEOUT=${SNOWFLAKE_TIMEOUT:-120}
      - SNOWFLAKE_MAX_RETRIES=${SNOWFLAKE_MAX_RETRIES:-3}
      - SNOWFLAKE_RETRY_DELAY=${SNOWFLAKE_RETRY_DELAY:-5}
      - SNOWFLAKE_POOL_SIZE=${SNOWFLAKE_POOL_SIZE:-5}
      - SNOWFLAKE_POOL_TIMEOUT=${SNOWFLAKE_POOL_TIMEOUT:-30}
      
      # For key pair authentication (uncomment if using)
      # - SNOWFLAKE_PRIVATE_KEY_PATH=/app/keys/snowflake_key.p8
      # - SNOWFLAKE_PRIVATE_KEY_PASSPHRASE=${SNOWFLAKE_PRIVATE_KEY_PASSPHRASE:-}
    
    # Mount volumes for configuration and keys (optional)
    volumes:
      - ./config:/app/config:ro
      # Uncomment for key pair authentication
      # - ./keys:/app/keys:ro
    
    # Restart policy
    restart: unless-stopped
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import server; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Optional: Network configuration
networks:
  default:
    name: mcp-network
    driver: bridge